name: introduction_to_ml_with_python
dependencies:
- ipython
- matplotlib
- numpy
- pandas
- python
- scipy
- ipython-notebook
- scikit-learn
- pillow
- spacy
- nltk
- pip:
    - watermark
    - graphviz
    - konlpy
    - JPype1-py3
prefix: /Users/rickypark/anaconda/envs/introduction_to_ml_with_python

